# Static recompilation cannot execute an Artemis instruction poke. Substitute
# definitions/sites in build copies, keeping the game's lifted source immutable.
file(READ "${CMAKE_CURRENT_SOURCE_DIR}/d2_cheats.v1.json" D2_CHEATS_JSON)
if(D2_GAME_VERSION STREQUAL "100")
    set(D2_CHEAT_PROFILE 0)
else()
    set(D2_CHEAT_PROFILE 1)
endif()
foreach(kind IN ITEMS exp sp shop damage)
    string(JSON D2_CHEAT_${kind}_ADDR GET "${D2_CHEATS_JSON}" versions ${D2_CHEAT_PROFILE} hooks ${kind})
endforeach()
set_property(GLOBAL PROPERTY D2_CHEAT_FOUND "")
function(d2_cheats_patch text_in text_out changed_out)
    set(text "${text_in}")
    set(changed FALSE)
    foreach(kind IN ITEMS exp sp shop)
        set(address "${D2_CHEAT_${kind}_ADDR}")
        set(signature "void func_${address}(ppu_context* ctx) {")
        string(FIND "${text}" "${signature}" found)
        if(NOT found EQUAL -1)
            string(REPLACE "${signature}" "void d2_cheat_original_${kind}(ppu_context* ctx) {" text "${text}")
            set_property(GLOBAL APPEND PROPERTY D2_CHEAT_FOUND ${kind})
            set(changed TRUE)
        endif()
    endforeach()
    if(D2_GAME_VERSION STREQUAL "100")
        set(site "        ctx->gpr[0] = ctx->gpr[0] - ctx->gpr[31];\n        vm_write64(ctx->gpr[9] + 0x1070, ctx->gpr[0]);\nloc_000E8958:")
        set(entity 26)
    else()
        set(site "        ctx->gpr[0] = ctx->gpr[0] - ctx->gpr[30];\n        vm_write64(ctx->gpr[9] + 0x1070, ctx->gpr[0]);\n        goto loc_000EEA40;")
        set(entity 25)
    endif()
    string(FIND "${text}" "${site}" found)
    if(NOT found EQUAL -1)
        string(REPLACE "        vm_write64(ctx->gpr[9] + 0x1070, ctx->gpr[0]);" "        ctx->gpr[0] = d2_cheats_damage(ctx->gpr[${entity}], ctx->gpr[9], ctx->gpr[0]);\n        vm_write64(ctx->gpr[9] + 0x1070, ctx->gpr[0]);" replacement "${site}")
        string(REPLACE "${site}" "${replacement}" text "${text}")
        string(PREPEND text "extern \"C\" unsigned long long d2_cheats_damage(unsigned long long, unsigned long long, unsigned long long);\n")
        set_property(GLOBAL APPEND PROPERTY D2_CHEAT_FOUND damage)
        set(changed TRUE)
    endif()
    set(${text_out} "${text}" PARENT_SCOPE)
    set(${changed_out} ${changed} PARENT_SCOPE)
endfunction()
